export const genreOptions = [
    { id: "1", value: "Action" },
    { id: "2", value: "Adventure" },
    { id: "3", value: "Comedy" },
    { id: "4", value: "Crime" },
    { id: "5", value: "Drama" },
    { id: "6", value: "Fantasy" },
    { id: "7", value: "Gossip" },
    { id: "8", value: "Historical" },
    { id: "9", value: "Horror" },
    { id: "10", value: "Josei" },
    { id: "11", value: "Magic" },
    { id: "12", value: "Mature" },
    { id: "13", value: "Mystery" },
    { id: "14", value: "Psychological" },
    { id: "15", value: "Romance" },
    { id: "16", value: "School Life" },
    { id: "17", value: "Sci-Fi" },
    { id: "18", value: "Seinen" },
    { id: "19", value: "Shoujo" },
    { id: "20", value: "Shounen" },
    { id: "21", value: "Slice of Life" },
    { id: "22", value: "Sports" },
    { id: "23", value: "Supernatural" },
    { id: "24", value: "Thriller" },
    { id: "25", value: "Tragedy" },
    { id: "26", value: "Yaoi" },
    { id: "27", value: "Yuri" },
];
