export const genres = [
    { id: "1", name: "Action" },
    { id: "2", name: "Adventure" },
    { id: "3", name: "Comedy" },
    { id: "4", name: "Crime" },
    { id: "5", name: "Drama" },
    { id: "6", name: "Fantasy" },
    { id: "7", name: "Gossip" },
    { id: "8", name: "Historical" },
    { id: "9", name: "Horror" },
    { id: "10", name: "Josei" },
    { id: "11", name: "Magic" },
    { id: "12", name: "Mature" },
    { id: "13", name: "Mystery" },
    { id: "14", name: "Psychological" },
    { id: "15", name: "Romance" },
    { id: "16", name: "School Life" },
    { id: "17", name: "Sci-Fi" },
    { id: "18", name: "Seinen" },
    { id: "19", name: "Shoujo" },
    { id: "20", name: "Shounen" },
    { id: "21", name: "Slice of Life" },
    { id: "22", name: "Sports" },
    { id: "23", name: "Supernatural" },
    { id: "24", name: "Thriller" },
    { id: "25", name: "Tragedy" },
    { id: "26", name: "Yaoi" },
    { id: "27", name: "Yuri" },
];
